---
name: Øystein Sørensen
position: "Associate Professor"
address: "Department of Psychology, University of Oslo"
www: osorensen.rbind.io
email: oystein.sorensen@psykologi.uio.no
twitter: SorensenOystein
github: osorensen
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::moderncv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)
source("../scripts/install.R")
```

```{r get data, include=FALSE}
## Education
edu <- read_delim(here("data", "education.csv"), delim = ";")

## Jobs
jobs <- read_delim(here::here("data", "jobs.csv"), delim = ";")

## Editorial boards
editor <- read_delim(here::here("data", "editor.csv"), delim = ";")

## Papers
get_papers <- function(bibfile){
  bib2df::bib2df(here::here("data", bibfile)) %>% 
    mutate(TITLE = str_remove_all(TITLE, "\\{|\\}")) %>% 
    mutate(MONTH = if_else(is.na(MONTH), "jan", MONTH),
      date = ymd(paste(YEAR, MONTH, "01", sep = "-"))) %>% 
    arrange(desc(date)) %>% 
    # put authors in one string
    mutate(
      author = map(AUTHOR, ~ glue_collapse(.x, sep = "; ")),
      author = str_replace(author, "^Vidal", "{Vidal")
      ) %>% 
    mutate(
      journal = if_else(is.na(JOURNAL), BOOKTITLE, JOURNAL),
      doi = textutils::TeXencode(DOI),
      where = ifelse(
        !is.na(doi),
        glue("<journal>. \\url{http://doi.org/<doi>}", .open = "<", .close = ">"),
        journal),
      first_author = str_detect(BIBTEXKEY, "sorensen") | 
        str_detect(BIBTEXKEY, "vitelli2017")
      ) %>% 
    arrange(desc(YEAR))
}

pubs <- get_papers("publications.bib")
preprints <- get_papers("preprints.bib")


## Teaching
teaching <- read_delim(here::here("data", "teaching.csv"), delim = ";") %>% 
  arrange(desc(when))

## Presentations
presentations <- read_csv(here::here("data", "presentations.csv")) %>% 
  arrange(desc(when))

## Training
training <- read_csv(here::here("data", "training.csv")) %>% 
  arrange(desc(end))

## Service
service <- read_csv(here::here("data", "service.csv"))
```

# Education
```{r}
detailed_entries(edu,
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = loc,
                 with = uni,
                 why = details)

```

# Experience

```{r research}
jobs %>%
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = company,
    where = where,
    why = details)
```

# Editorial Boards

```{r}
editor %>%
  detailed_entries(
    what = role,
    when = glue("{start_date}--{end_date}"),
    with = journal
  )
```




# First Author Publications

```{r}
pubs %>% 
  filter(first_author) %>% 
  detailed_entries(
    what = author,
    when = YEAR,
    with = TITLE,
    where = where,
    .protect = FALSE
  )
```

# Non First Author Publications

```{r}
pubs %>% 
  filter(!first_author) %>% 
  detailed_entries(
    what = author,
    when = YEAR,
    with = TITLE,
    where = where,
    .protect = FALSE
  )
```


# Preprints

```{r}
preprints %>%
  detailed_entries(
    what = author,
    when = YEAR,
    with = TITLE,
    where = where,
    .protect = FALSE
  )
```



# Software

```{r}
df <- tribble(~what, ~when, ~with, ~where, ~why,
              "hdme: High-Dimensional Regression with Measurement Error",
              2018,
              "Sørensen Ø",
              "https://cran.r-project.org/package=hdme",
              "Author and maintainer",
              
              "BayesMallows: Bayesian Preference Learning with the Mallows Rank Model",
              2018,
              "Sørensen Ø et al.",
              "https://cran.r-project.org/package=BayesMallows",
              "Author and maintainer",
              
              "metagam: Meta-Analysis of Generalized Additive Models",
              2020,
              "Sørensen Ø., Brandmaier AM, and Mowinckel AM",
              "https://cran.r-project.org/package=metagam",
              "Author and maintainer",
              
              "BayesianLaterality: Predict Brain Asymmetry Based on Handedness and Dichotic Listening",
              2020,
              "Sørensen Ø.",
              "https://cran.r-project.org/package=BayesianLaterality",
              "Author and maintainer",
              
              "cellmigRation: Track Cells, Analyze Cell Trajectories and Compute Migration Statistics",
              2021,
              "Ghannoum S, Fantini D, Leoncio W, and Sørensen Ø",
              "https://bioconductor.org/packages/cellmigRation/",
              "Contributor"
              )
```


```{r}
df %>% 
  arrange(desc(when)) %>% 
  detailed_entries(what = what, when = when, with = with, where = where, why = why)
```


*See [my GitHub](https://github.com/osorensen/) for a complete overview of my software both released and in development.*

<!-- # Teaching -->

<!-- ```{r} -->
<!-- teaching %>%  -->
<!--   detailed_entries(what = what, when = when, with = with, why = details) -->
<!-- ``` -->

<!-- # Presentations -->

<!-- ```{r} -->
<!-- presentations %>%  -->
<!--   detailed_entries(what = what, -->
<!--                    when = when, -->
<!--                    with = with, -->
<!--                    where = where, -->
<!--                    why = why, -->
<!--                    .protect = TRUE) -->
<!-- ``` -->

<!-- # Service -->

<!-- ```{r} -->
<!-- service %>%  -->
<!--   detailed_entries(with = type, why = details) -->
<!-- ``` -->
